name: bioFM
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - pip=22.3.1
  - python=3.10.9
  - wheel=0.37.1
  - pip:
      - appdirs==1.4.4
      - charset-normalizer==3.0.1
      - chardet==4.0.0
      - click==8.1.3
      - cloudpickle==2.2.1
      - dash==2.8.1
      - dash-core-components==2.0.0
      - dash-cytoscape==0.3.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dill==0.3.6
      - docker-pycreds==0.4.0
      - easydict==1.10
      - filelock==3.10.2
      - flask==2.2.2
      - gevent==22.10.2
      - gitdb==4.0.10
      - gitpython==3.1.31
      - greenlet==2.0.2
      - h5py==3.8.0
      - imageio==2.25.0
      - interpret==0.3.0
      - interpret-core==0.3.0
      - itsdangerous==2.1.2
      - joblib==1.2.0
      - lime==0.2.0.1
      - llvmlite==0.39.1
      - markupsafe==2.1.2
      - mpmath==1.3.0
      - multiprocess==0.70.14
      - networkx==3.0
      - ninja==1.11.1
      - pathtools==0.1.2
      - pandas
      - plotly==5.13.0
      - protobuf==4.22.1
      - pynndescent==0.5.8
      - pywavelets==1.4.1
      - requests==2.28.2
      - salib==1.4.7
      - scikit-image==0.19.3
      - scikit-learn==1.2.1
      - scipy
      - seaborn
      - sentry-sdk==1.17.0
      - setproctitle==1.3.2
      - shap==0.41.0
      - skope-rules==1.0.1
      - slicer==0.0.7
      - smmap==5.0.0
      - sympy==1.11.1
      - tabulate==0.9.0
      - tenacity==8.2.0
      - tensorboard
      - threadpoolctl==3.1.0
      - tifffile==2023.2.3
      - torch==2.0.0
      - torchvision==0.15.1
      - tqdm==4.64.1
      - treeinterpreter==0.2.3
      - typing-extensions==4.5.0
      - umap-learn==0.5.3
      - wandb==0.14.0
      - werkzeug==2.2.2
      - zeroc-ice==3.6.5
      - zope-event==4.6
      - zope-interface==5.5.2
